apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: Q3JlZG9JblZveE1vcnRpcw==   # base64 z 'password'
  POSTGRES_USER: QXp5cg==           # base64 z 'user'
  POSTGRES_DB: UmV2aWV3cw==             # base64 z 'appdb'